version: "3.6"

networks:
  tempo-network:
    name: tempo-network
 
services:

  orchestrator:
    build:
      context: .

    environment:
      SPRING_PROFILES_ACTIVE: db

    ports:
      - "8080:8080"

    networks:
      - tempo-network
