# SpringBoot Properties: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

spring:
  application:
    name: teams-service

logging:
  level:
    org.springframework.core.env: WARN
    org.springframework.jndi: WARN
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    io.tempo.teams: DEBUG

springdoc:
  api-docs:
    path: /docs/openapi
  swagger-ui:
    path: /docs/swagger/index.html

server:
  error:
    whitelabel:
      enabled: false

  port: 8080
  tomcat:
    accesslog:
      enabled: true
      # /dev/stdout is standard output, so we want tomcat
      # to write to that file descriptor.
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "[ACCESS] %h %t %{org.apache.catalina.AccessLog.RemoteAddr}r http_method=%m http_path=%U http_query=%q http_protocol=%H http_status=%s latency_total=%Dms latency_commit=%Fms response_size=%Bbytes %S %u tid=%{X-Tempo-Tid}i uid=%{X-Tempo-Uid}i x_b3_traceid=%{X-B3-TraceId}o"